### ISSUE TITLE
Remove description field from game

### ISSUE THREAD

**Issue by johnpooch** [johnpooch/diplomacy#185]
**Story**
As a user I want to not have to fill in the `description` field when creating a game because it makes making a game less convenient and the field doesn't appear anywhere.

**Acceptance criteria**
When the user is creating a game, the description field should not appear. The description should not appear on the game in the browse view. The field should be removed from the game model entirely.

**Tasks**
- [ ] Remove the description field from the `Game` model
- [ ] Remove the description field from the `GameSerializer`
- [ ] Remove the description field from the Create Game form
