### ISSUE TITLE
Make password rules more strict

### ISSUE THREAD

**Issue by johnpooch** [johnpooch/diplomacy#192]
**Story**
As a developer I want to ensure that passwords are reasonably robust so that user accounts aren't easily compromised.

**Acceptance Criteria**
When a user tries to register with a weak password they should see an error message. When a user tries to reset their password to a weak password they should see a warning.

**Tasks**
- [ ] Set up service to have basic strictness on passwords
- [ ] Add tests to ensure that this strictness is enforced by all password views
- [ ] Ensure that error messages are presented on the client.
